openapi: 3.0.0
info:
  title: Microsoft Graph API - SharePoint List Query
  description: API to retrieve SharePoint list items with expanded fields
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /sites/reshmee.sharepoint.com,541d6ad1-322f-419d-8575-5309a29c3cf8,6b96c932-79a5-4f2a-91dc-41689290ebe7/lists/User Information List/items?$filter=fields/Title eq 'Reshmee Auckloo'&$expand=fields:
    get:
      summary: Retrieve list items with selected fields
      operationId: getUserInformation
      tags:
        - SharePoint
      parameters:
      - name: Prefer
        in: header
        description: Allows non-indexed queries to proceed with a warning
        required: false
        schema:
          type: string
          example: "HonorNonIndexedQueriesWarningMayFailRandomly"
      - name: expand
        in: query
        description: Expand fields in response
        required: false
        schema:
          type: string
          example: "fields(select=id,EMail)"
      responses:
        "200":
          description: Successful retrieval of list items
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@odata.context":
                    type: string
                    description: Metadata context URL
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Item ID
                        createdDateTime:
                          type: string
                          format: date-time
                          description: Creation timestamp
                        lastModifiedDateTime:
                          type: string
                          format: date-time
                          description: Last modification timestamp
                        webUrl:
                          type: string
                          format: uri
                          description: Web URL of the item
                        createdBy:
                          type: object
                          properties:
                            user:
                              type: object
                              properties:
                                displayName:
                                  type: string
                                  description: Creator name
                        lastModifiedBy:
                          type: object
                          properties:
                            user:
                              type: object
                              properties:
                                displayName:
                                  type: string
                                  description: Modifier name
                        fields:
                          type: object
                          properties:
                            id:
                              type: string
                              description: List item ID
                            EMail:
                              type: string
                              description: Email associated with the item
security:
  - azureaadv2: []
components:
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: >-
            https://login.microsoftonline.com/39f0e149-6ce0-483e-8acf-b6faa229a203/oauth2/v2.0/authorize
          tokenUrl: >-
            https://login.microsoftonline.com/39f0e149-6ce0-483e-8acf-b6faa229a203/oauth2/v2.0/token
          scopes:
            User.Read: Read user profile
            Directory.Read.All: Read directory data
            Tasks.ReadWrite: Read and write all tasks
            Mail.Send: Send mail as a user
            SharePoint.ReadWrite.All: >-
              Read and write items in all site collections without a signed-in
              user